Solution of 2-module 1-2-3-task
js-tasks-ru/jsbasic-20231109_nikita023 pull request #4
Opened 2023-11-22 11:51 UTC by 23sns

2023-11-22 11:52 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-23 12:49 UTC, SinimaWath requested changes

2023-11-23 12:49 UTC, SinimaWath commented on 2-module/1-task/index.js
> +  if (typeof salaries[key] === 'number' && salaries[key] !== NaN && salaries[key] !== Infinity && salaries[key] !== -Infinity && isNaN(salaries[key]) === false) {
`salaries[key] !== NaN` - эта проверка явно лишняя.

В целом тут можно упростить если заиспользовать метод: `typeof salaries[key] === 'number' && isFinite(salaries[key])` или `Number.isFinite(salaries[key])`

2023-11-23 12:49 UTC, SinimaWath commented on 2-module/2-task/index.js
> +  }
Непонятно, что именно проверяет, этот if. Без него, так же все будет корректно работать

2023-11-23 15:06 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-26 19:24 UTC, SinimaWath approved these changes
все круто

2023-11-26 19:24 UTC, merged